### ISSUE TITLE
Why ddpm part in p-diff use AE_CNN rather than DDPM as default? 

### ISSUE THREAD

**Issue by hanbakasuki** [NUS-HPC-AI-Lab/Neural-Network-Diffusion#14]
Hi,

I tried to reproduce the work like what the paper mentions but found the code different from what the paper described. In the config file, ddpm.yaml set the model as AE_CNN which convert random noise to latent representations:

```
model:
  arch:
    _target_: core.module.wrapper.ema.EMA
    model:
      _target_: core.module.modules.unet.AE_CNN_bottleneck
      in_channel: 2
      in_dim: 4

```

It appears that in addition to the autoencoder used to convert the trained network parameters to the latent representation, the same structure of the autoencoder is used in the process of synthesizing the latent representation
